name: bootstrap_for_pub
description: Bootstrap's files, in a pub package. Contains
             Bootstrap 3.2.
             Included is a transformer to swap the CSS for a CDN version.
authors:
- Bootstrap core team
- Victor Berchet <victor@suumit.com>
- Seth Ladd <sethladd@gmail.com>
version: 3.3.0+1
homepage: https://github.com/sethladd/bootstrap_for_pub
dependencies:
  barback: ">=0.14.1+3 <0.15.0"
  html5lib: ">=0.11.0+1 <0.12.0"
